FROM golang:alpine as builder
RUN mkdir /build 
ADD hello.go /build/
WORKDIR /build 
RUN CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -ldflags '-extldflags "-static"' -o hello .
FROM scratch
COPY --from=builder /build/hello /app/
WORKDIR /app
EXPOSE 8030 
CMD ["./hello"]